# Generated by Django 3.2.7 on 2021-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='background image'),
        ),
    ]
