# Generated by Django 3.2.7 on 2021-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='greet',
            field=models.TextField(default='We would like to wish all our valuable customers a Merry Christmas and Happy New Year and Holiday Season!', verbose_name='content'),
        ),
    ]
