# Generated by Django 3.2.7 on 2021-10-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0002_carddata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='add_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carddata',
            name='add_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carddata',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carddata',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
