# Generated by Django 3.2.7 on 2021-10-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0003_auto_20211020_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='add_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pop up end date'),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='add_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pop up start date'),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
