# Generated by Django 3.2.7 on 2021-10-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecards', '0004_auto_20211020_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='is_popup_active',
            field=models.BooleanField(default=False),
        ),
    ]
